### ISSUE TITLE
How to use with STM32CubeIDE and Blue Pill

### ISSUE THREAD

**Issue by MickGyver** [IntergatedCircuits/USBDevice4Cube#10]
This project looks promising, I'm not having any luck using it iwith STM32CubeIDE 1.4.0 and a Blue Pill board (STM32F103C8T6). Could you please give some hints what files are needed and where? I guess I need both this wrapper project and the USBDevice project but I don't know how to set it all up...

**Comment by MickGyver** [comment]
I copied files from the two repositories and was able to compile the project but with warnings that I need to solve. For example this one in HAL_USBD_Setup():
`../Core/Src/hal_usb.c:34:36: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     UsbDevice->Callbacks.DepDeinit = HAL_PCD_MspDeInit;`

**Comment by MickGyver** [comment]
I guess what I'm not really understanding is how to setup the hal_usb.c file for STM32F103, since things seem quite different from your example.

**Comment by benedekkupper** [comment]
It's best if you generate Cube code for the USB peripheral, then copy the related MspInit and MspDeInit calls to hal_usb.c, replace the OTG_FS_IRQHandler and OTG_FS_IRQn to the F103's USB interrupt vector, then remove the generated USB peripheral code entirely.

For proper operation you'll need to connect 1.5K resistor between USB DP and a free GPIO output, and implement a UsbDevice->Callbacks.ConnectCtrl callback as well, to set this pin depending on the parameter.

**Comment by MickGyver** [comment]
Thanks for your reply. I'm using Blue Pill boards that have a 1.5K resistor between USB DP and 3.3V. This is the code I have in hal_usb.c now. It gives me some warnings and the device is not recognised when plugged into a usb port. I'm still missing something I guess.

```
void HAL_PCD_MspInit(PCD_HandleTypeDef* pcdHandle)
{
  if(pcdHandle->Instance == USB)
  {
    __HAL_RCC_USB_CLK_ENABLE();
    HAL_NVIC_SetPriority(USB_LP_CAN1_RX0_IRQn, 0, 0);
    HAL_NVIC_EnableIRQ(USB_LP_CAN1_RX0_IRQn);
  }
}

void HAL_PCD_MspDeInit(PCD_HandleTypeDef* pcdHandle)
{
  if(pcdHandle->Instance == USB)
  {
    __HAL_RCC_USB_CLK_DISABLE();
    HAL_NVIC_DisableIRQ(USB_LP_CAN1_RX0_IRQn);
  }
}

void HAL_USBD_Setup(void)
{
    USB_INST2HANDLE(UsbDevice, USB);
    UsbDevice->Callbacks.DepInit = HAL_PCD_MspInit;
    UsbDevice->Callbacks.DepDeinit = HAL_PCD_MspDeInit;
}

void USB_LP_CAN1_RX0_IRQHandler(void);

void USB_LP_CAN1_RX0_IRQHandler(void)
{
  USB_vIRQHandler(UsbDevice);
}

**Comment by benedekkupper** [comment]
I meant to copy the statements in these functions, the parameter type should be void*, and the if should be removed.
In general these should do 3 things:
1. Set the gpios to usb alternate mode
2. Set the clock tree of the usb so it gets clocked at 48 MHz
3. Configure the usb interrupt(s)

So you'll have to get these right at least for your usb to work.

**Comment by MickGyver** [comment]
Thank you very much! I figured yesterday that only the statements needed copying, I first thought that the entire functions needed to be implemented. have it working now, below is how hal_usb.h looks now. (it worked before configuring the GPIO pins also, but wouldn't rely on it).

```
void HAL_USB_MspInit(void * handle)
{
  GPIO_InitTypeDef GPIO_InitStruct;
  GPIO_InitStruct.Pin = GPIO_PIN_11 | GPIO_PIN_12;
  GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_HIGH;
  HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);

  __HAL_RCC_USB_CLK_ENABLE();
  HAL_NVIC_SetPriority(USB_LP_CAN1_RX0_IRQn, 0, 0);
  HAL_NVIC_EnableIRQ(USB_LP_CAN1_RX0_IRQn);
}
void HAL_USB_MspDeInit(void * handle)
{
  HAL_GPIO_DeInit(GPIOA, GPIO_PIN_11 | GPIO_PIN_12);
  __HAL_RCC_USB_CLK_DISABLE();
  HAL_NVIC_DisableIRQ(USB_LP_CAN1_RX0_IRQn);
}
void HAL_USBD_Setup(void)
{
    USB_INST2HANDLE(UsbDevice, USB);
    UsbDevice->Callbacks.DepInit = HAL_USB_MspInit;
    UsbDevice->Callbacks.DepDeinit = HAL_USB_MspDeInit;
}
```

The IRQ handler is implemented in stm32f1xx_it.c:

```
void USB_LP_CAN1_RX0_IRQHandler(void)
{
  USB_vIRQHandler(UsbDevice);
}
```

**Comment by DCNick3** [comment]
It seems that STM32F103C8T6 has something funky going on with its GPIO config: CubeMX doesn't seem generate GPIO configuration for USB at all. Maybe it's because it's in the required mode for USB already at boot?

**Comment by benedekkupper** [comment]
> Maybe it's because it's in the required mode for USB already at boot?

I'd rather guess that it doesn't generate USB code because you didn't select the USB_DEVICE in Middlewares. Which is fine if you are going to use this stack instead. From the above discussion you shouldn't have any problem adding the necessary glue code to make this work.
