### ISSUE TITLE
Overflow in IN endpoint handler when using DMA

### ISSUE THREAD

**Issue by igorizyumin** [IntergatedCircuits/USBDevice4Cube#2]
The following line does not handle the case when Progress is less than the max packet size.  This causes Progress to wraparound and causes enumeration to fail when DMA is enabled (since the device descriptor is less than the packet size).

https://github.com/IntergatedCircuits/USBDevice4Cube/blob/5871c435dee1511c799e577a79bbaa1010f794e5/XPD_USB/xpd_usb_otg.c#L1114

I changed it to the following, which fixed the problem.
```
if (pxEP->Transfer.Progress > pxEP->MaxPacketSize)
    pxEP->Transfer.Progress -= pxEP->MaxPacketSize;
else
    pxEP->Transfer.Progress = 0;
```

**Comment by benedekkupper** [comment]
Good catch! I reviewed the DMA transfer handling a bit, and found that the OUT direction is also completely flawed. I pushed an update that hopefully resolves these issues, looking forward to your feedback on it.
